In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [13]:
# %load test.py
import numpy as np

a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [14]:
%run test.py

[1 2 3]
